"""
Feedback delivery endpoint.

Provides a GET endpoint to retrieve the latest comparison results
and feedback generated by the dance comparison pipeline.
Uses FastAPI with CORS, matching the pattern of fileGetter.py.
"""
import os
import sys
import json
from datetime import datetime
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse
import uvicorn

# Ensure project root is on path
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(CURRENT_DIR)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

app = FastAPI()

# Configure CORS (same as fileGetter.py)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Storage directory for results (root/data/)
DATA_DIR = os.path.join(ROOT_DIR, 'data')


def _find_latest_session():
    """Find the most recent session directory inside data/."""
    if not os.path.isdir(DATA_DIR):
        return None
    sessions = sorted(
        [d for d in os.listdir(DATA_DIR)
         if os.path.isdir(os.path.join(DATA_DIR, d))],
        reverse=True,
    )
    return sessions[0] if sessions else None


def _load_results(session_id):
    """Load the results JSON for a given session."""
    results_path = os.path.join(DATA_DIR, session_id, 'results.json')
    if not os.path.isfile(results_path):
        return None
    with open(results_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_results(session_id, results):
    """
    Persist comparison results to disk as JSON.

    Called by fileGetter after process_videos completes.
    Converts numpy arrays to lists for JSON serialization.

    Args:
        session_id: Session directory name (e.g. '20260306_134500').
        results: Dict returned by process_videos (with feedback attached).
    """
    import numpy as np

    session_dir = os.path.join(DATA_DIR, session_id)
    os.makedirs(session_dir, exist_ok=True)

    # Make results JSON-serializable (convert numpy arrays)
    serializable = {}
    for key, value in results.items():
        if isinstance(value, np.ndarray):
            serializable[key] = value.tolist()
        elif isinstance(value, dict):
            serializable[key] = {
                k: v.tolist() if isinstance(v, np.ndarray) else v
                for k, v in value.items()
            }
        else:
            serializable[key] = value

    results_path = os.path.join(session_dir, 'results.json')
    with open(results_path, 'w', encoding='utf-8') as f:
        json.dump(serializable, f, indent=2)


# ── Endpoints ────────────────────────────────────────────────────────────


@app.get("/feedback")
async def get_feedback(session_id: str = Query(default=None)):
    """
    Retrieve comparison feedback for a session.

    Query params:
        session_id: Optional — if omitted, returns the latest session.

    Returns:
        JSON with overall_score, skeleton_score, trajectory_score,
        mask_score, per_joint_scores, feedback messages, etc.
    """
    if session_id is None:
        session_id = _find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    results = _load_results(session_id)
    if results is None:
        raise HTTPException(
            status_code=404,
            detail=f"No results found for session '{session_id}'.",
        )

    # Build video URL if the video file exists
    video_file = os.path.join(DATA_DIR, session_id, 'feedback_video.mp4')
    video_url = f"/feedback/video?session_id={session_id}" if os.path.isfile(video_file) else None

    # Return a frontend-friendly subset
    return JSONResponse(content={
        "session_id": session_id,
        "overall_score": results.get("overall_score"),
        "skeleton_score": results.get("skeleton_score"),
        "trajectory_score": results.get("trajectory_score"),
        "mask_score": results.get("mask_score"),
        "timing_cost": results.get("timing_cost"),
        "per_joint_scores": results.get("per_joint_scores"),
        "feedback": results.get("feedback", []),
        "feedback_video_url": video_url,
    })


@app.get("/feedback/detailed")
async def get_detailed_feedback(session_id: str = Query(default=None)):
    """
    Retrieve full comparison results including per-frame data.

    Useful for visualisation / charting on the frontend.
    """
    if session_id is None:
        session_id = _find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    results = _load_results(session_id)
    if results is None:
        raise HTTPException(
            status_code=404,
            detail=f"No results found for session '{session_id}'.",
        )

    return JSONResponse(content={
        "session_id": session_id,
        **results,
    })


@app.get("/feedback/video")
async def get_feedback_video(session_id: str = Query(default=None)):
    """
    Stream the feedback comparison video for a session.

    Query params:
        session_id: Optional — if omitted, uses the latest session.
    """
    if session_id is None:
        session_id = _find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    video_path = os.path.join(DATA_DIR, session_id, 'feedback_video.mp4')
    if not os.path.isfile(video_path):
        raise HTTPException(
            status_code=404,
            detail=f"No feedback video found for session '{session_id}'.",
        )

    return FileResponse(
        video_path,
        media_type='video/mp4',
        filename='feedback_video.mp4',
    )


@app.get("/sessions")
async def list_sessions():
    """List all available session IDs."""
    if not os.path.isdir(DATA_DIR):
        return JSONResponse(content={"sessions": []})

    sessions = sorted(
        [d for d in os.listdir(DATA_DIR)
         if os.path.isdir(os.path.join(DATA_DIR, d))],
        reverse=True,
    )
    return JSONResponse(content={"sessions": sessions})


if __name__ == "__main__":
    print("Starting feedback server on http://localhost:8001")
    uvicorn.run(app, host="127.0.0.1", port=8001)
