"""
Feedback delivery endpoint.

Provides a GET endpoint to retrieve the latest comparison results
and feedback generated by the dance comparison pipeline.
Uses FastAPI with CORS, matching the pattern of fileGetter.py.
"""
import asyncio
from contextlib import asynccontextmanager
import json
import os
import sys

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
import uvicorn

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(CURRENT_DIR)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Handle application startup and shutdown lifecycle.

    On Windows, resets SIGINT to default so Ctrl+C stops the server
    and suppresses spurious ConnectionResetError from the Proactor loop.
    """
    import sys
    if sys.platform == "win32":
        import signal
        signal.signal(signal.SIGINT, signal.SIG_DFL)

        loop = asyncio.get_running_loop()

        def _suppress_proactor_errors(loop, context):
            exception = context.get("exception")
            if isinstance(exception, ConnectionResetError):
                return
            loop.default_exception_handler(context)

        loop.set_exception_handler(_suppress_proactor_errors)
    yield


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR = os.path.join(ROOT_DIR, 'data')


class FeedbackSender:
    """Groups feedback data-access logic: locating sessions
    and loading results JSON."""

    @staticmethod
    def find_latest_session() -> str | None:
        """Find the most recent session directory inside data/.

        Returns:
            The session directory name, or None if no sessions exist.
        """
        if not os.path.isdir(DATA_DIR):
            return None
        sessions = sorted(
            [d for d in os.listdir(DATA_DIR)
             if os.path.isdir(os.path.join(DATA_DIR, d))],
            reverse=True,
        )
        return sessions[0] if sessions else None

    @staticmethod
    def load_results(session_id: str) -> dict | None:
        """Load the results JSON for a given session.

        Args:
            session_id: Session directory name (e.g. '20260306_134500').

        Returns:
            Parsed dict from results.json, or None if the file does not exist.
        """
        results_path = os.path.join(DATA_DIR, session_id, 'results.json')
        if not os.path.isfile(results_path):
            return None
        with open(results_path, 'r', encoding='utf-8') as f:
            return json.load(f)



# ── Endpoints ────────────────────────────────────────────────────────────


@app.get("/feedback")
async def get_feedback(
    session_id: str | None = Query(default=None),
) -> JSONResponse:
    """Retrieve comparison feedback for a session.

    Query params:
        session_id: Optional — if omitted, returns the latest session.

    Returns:
        JSON with overall_score, skeleton_score, trajectory_score,
        mask_score, per_joint_scores, feedback messages, etc.
    """
    if session_id is None:
        session_id = FeedbackSender.find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    results = FeedbackSender.load_results(session_id)
    if results is None:
        raise HTTPException(
            status_code=404,
            detail=f"No results found for session '{session_id}'.",
        )

    video_file = os.path.join(DATA_DIR, session_id, 'feedback_video.mp4')
    video_url = (
        f"/feedback/video?session_id={session_id}"
        if os.path.isfile(video_file)
        else None
    )

    return JSONResponse(content={
        "session_id": session_id,
        "overall_score": results.get("overall_score"),
        "skeleton_score": results.get("skeleton_score"),
        "trajectory_score": results.get("trajectory_score"),
        "mask_score": results.get("mask_score"),
        "timing_cost": results.get("timing_cost"),
        "per_joint_scores": results.get("per_joint_scores"),
        "feedback": results.get("feedback", []),
        "timeline_markers": results.get("timeline_markers", []),
        "feedback_video_url": video_url,
    })


@app.get("/feedback/detailed")
async def get_detailed_feedback(
    session_id: str | None = Query(default=None),
) -> JSONResponse:
    """Retrieve full comparison results including per-frame data.

    Useful for visualisation / charting on the frontend.
    """
    if session_id is None:
        session_id = FeedbackSender.find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    results = FeedbackSender.load_results(session_id)
    if results is None:
        raise HTTPException(
            status_code=404,
            detail=f"No results found for session '{session_id}'.",
        )

    return JSONResponse(content={
        "session_id": session_id,
        **results,
    })


@app.get("/feedback/video")
async def get_feedback_video(
    session_id: str | None = Query(default=None),
) -> FileResponse:
    """Stream the feedback comparison video for a session.

    Query params:
        session_id: Optional — if omitted, uses the latest session.
    """
    if session_id is None:
        session_id = FeedbackSender.find_latest_session()
        if session_id is None:
            raise HTTPException(status_code=404, detail="No sessions found.")

    video_path = os.path.join(DATA_DIR, session_id, 'feedback_video.mp4')
    if not os.path.isfile(video_path):
        raise HTTPException(
            status_code=404,
            detail=f"No feedback video found for session '{session_id}'.",
        )

    return FileResponse(
        video_path,
        media_type='video/mp4',
        filename='feedback_video.mp4',
    )


@app.get("/sessions")
async def list_sessions() -> JSONResponse:
    """List all available session IDs."""
    if not os.path.isdir(DATA_DIR):
        return JSONResponse(content={"sessions": []})

    sessions = sorted(
        [d for d in os.listdir(DATA_DIR)
         if os.path.isdir(os.path.join(DATA_DIR, d))],
        reverse=True,
    )
    return JSONResponse(content={"sessions": sessions})


if __name__ == "__main__":
    print("Starting feedback server on http://localhost:8001")
    uvicorn.run(app, host="127.0.0.1", port=8001)
